# Copyright (C) 2026 Ericsson AB
# SPDX-License-Identifier: MIT
"""Tests for force_checkout_branch escalation (dirty devtool workspaces)."""
import subprocess
from pathlib import Path

from shared.git_runner import force_checkout_branch, run_capture


def _git(cwd: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(['git', *args], cwd=cwd, capture_output=True,
                          text=True, check=True)


def _current_branch(cwd: Path) -> str:
    return run_capture(['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
                       cwd=cwd).stdout.strip()


def _make_repo(tmp_path: Path) -> Path:
    """Repo with a CVE branch and a devtool branch that differ in configure."""
    repo = tmp_path / 'jq'
    repo.mkdir()
    _git(repo, 'init', '-q', '-b', 'main')
    _git(repo, 'config', 'user.email', 'test@example.com')
    _git(repo, 'config', 'user.name', 'Test')
    (repo / 'configure').write_text('base\n', encoding='utf-8')
    (repo / 'Makefile.in').write_text('base\n', encoding='utf-8')
    _git(repo, 'add', '-A')
    _git(repo, 'commit', '-qm', 'base')

    _git(repo, 'checkout', '-q', '-b', 'CVE-2026-39956')
    (repo / 'configure').write_text('cve branch\n', encoding='utf-8')
    _git(repo, 'commit', '-qam', 'cve')

    _git(repo, 'checkout', '-q', '-b', 'devtool', 'main')
    (repo / 'configure').write_text('devtool branch\n', encoding='utf-8')
    _git(repo, 'commit', '-qam', 'devtool')
    return repo


def test_plain_checkout_path(tmp_path):
    """A clean tree still switches branches without any cleanup."""
    repo = _make_repo(tmp_path)
    assert force_checkout_branch(repo, 'CVE-2026-39956') is True
    assert _current_branch(repo) == 'CVE-2026-39956'


def test_dirty_tracked_files_do_not_block_checkout(tmp_path):
    """Regenerated autotools output must not abort the branch switch.

    Reproduces the reported failure: the build regenerates tracked files
    (configure, Makefile.in, ...) so `git checkout <cve-branch>` aborts with
    "Your local changes to the following files would be overwritten".
    """
    repo = _make_repo(tmp_path)
    (repo / 'configure').write_text('regenerated by autoreconf\n', encoding='utf-8')
    (repo / 'Makefile.in').write_text('regenerated\n', encoding='utf-8')

    plain = run_capture(['git', 'checkout', 'CVE-2026-39956'], cwd=repo)
    assert plain.returncode != 0  # pre-condition: plain checkout fails

    assert force_checkout_branch(repo, 'CVE-2026-39956') is True
    assert _current_branch(repo) == 'CVE-2026-39956'
    assert (repo / 'configure').read_text(encoding='utf-8') == 'cve branch\n'


def test_unmerged_index_does_not_block_checkout(tmp_path):
    """An aborted cherry-pick leaving conflict markers still switches back."""
    repo = _make_repo(tmp_path)
    conflict = run_capture(['git', 'cherry-pick', 'CVE-2026-39956'], cwd=repo)
    assert conflict.returncode != 0  # pre-condition: conflicted state

    assert force_checkout_branch(repo, 'CVE-2026-39956') is True
    assert _current_branch(repo) == 'CVE-2026-39956'


def test_untracked_file_shadowing_tracked_path(tmp_path):
    """Untracked copies of devtool files are cleaned when they block checkout."""
    repo = _make_repo(tmp_path)
    _git(repo, 'checkout', '-q', 'main')
    # aclocal.m4 exists only on the CVE branch; an untracked copy blocks checkout
    _git(repo, 'checkout', '-q', 'CVE-2026-39956')
    (repo / 'aclocal.m4').write_text('on cve branch\n', encoding='utf-8')
    _git(repo, 'add', 'aclocal.m4')
    _git(repo, 'commit', '-qm', 'add aclocal')
    _git(repo, 'checkout', '-q', 'devtool')
    (repo / 'aclocal.m4').write_text('untracked copy\n', encoding='utf-8')

    plain = run_capture(['git', 'checkout', 'CVE-2026-39956'], cwd=repo)
    assert plain.returncode != 0  # pre-condition: untracked file blocks it

    assert force_checkout_branch(repo, 'CVE-2026-39956') is True
    assert _current_branch(repo) == 'CVE-2026-39956'
    assert (repo / 'aclocal.m4').read_text(encoding='utf-8') == 'on cve branch\n'


def test_oe_local_files_preserved(tmp_path):
    """The clean escalation must never remove oe-local-files."""
    repo = _make_repo(tmp_path)
    _git(repo, 'checkout', '-q', 'CVE-2026-39956')
    (repo / 'aclocal.m4').write_text('on cve branch\n', encoding='utf-8')
    _git(repo, 'add', 'aclocal.m4')
    _git(repo, 'commit', '-qm', 'add aclocal')
    _git(repo, 'checkout', '-q', 'devtool')
    (repo / 'aclocal.m4').write_text('untracked copy\n', encoding='utf-8')
    local = repo / 'oe-local-files'
    local.mkdir()
    (local / 'fix.patch').write_text('keep me\n', encoding='utf-8')

    assert force_checkout_branch(repo, 'CVE-2026-39956') is True
    assert (local / 'fix.patch').read_text(encoding='utf-8') == 'keep me\n'


def test_dirty_submodule_content_does_not_block_checkout(tmp_path):
    """Modified submodule content is reset and the gitlink re-synced.

    Mirrors the jq/modules/oniguruma layout where a build regenerates
    autotools output inside the submodule.
    """
    sub = tmp_path / 'oniguruma'
    sub.mkdir()
    _git(sub, 'init', '-q', '-b', 'main')
    _git(sub, 'config', 'user.email', 'test@example.com')
    _git(sub, 'config', 'user.name', 'Test')
    (sub / 'configure').write_text('sub base\n', encoding='utf-8')
    _git(sub, 'add', '-A')
    _git(sub, 'commit', '-qm', 'sub base')

    repo = _make_repo(tmp_path)
    _git(repo, 'checkout', '-q', 'CVE-2026-39956')
    _git(repo, '-c', 'protocol.file.allow=always', 'submodule', 'add', '-q',
         str(sub), 'modules/oniguruma')
    _git(repo, 'commit', '-qm', 'add submodule')
    _git(repo, 'checkout', '-q', 'devtool')

    subdir = repo / 'modules' / 'oniguruma'
    subdir.mkdir(parents=True, exist_ok=True)
    (subdir / 'configure').write_text('regenerated\n', encoding='utf-8')
    # Parent-level regenerated file forces the escalation path
    (repo / 'configure').write_text('regenerated by autoreconf\n', encoding='utf-8')

    plain = run_capture(['git', 'checkout', 'CVE-2026-39956'], cwd=repo)
    assert plain.returncode != 0  # pre-condition: plain checkout fails

    assert force_checkout_branch(repo, 'CVE-2026-39956') is True
    assert _current_branch(repo) == 'CVE-2026-39956'
    status = run_capture(['git', 'status', '--porcelain'], cwd=repo).stdout
    assert status.strip() == ''
    assert (subdir / 'configure').read_text(encoding='utf-8') == 'sub base\n'


def test_missing_branch_returns_false(tmp_path):
    """A non-existent branch fails cleanly instead of raising."""
    repo = _make_repo(tmp_path)
    assert force_checkout_branch(repo, 'CVE-does-not-exist') is False
