# Copyright (C) 2026 Ericsson AB
# SPDX-License-Identifier: MIT
"""Consolidated git/subprocess runner used by cve_corrector and cve_agent.

Provides two levels of abstraction:
- run_capture(): low-level, returns CompletedProcess (for corrector)
- run_git_stdout(): high-level git-only, returns stdout str (for agent)
"""
import subprocess
from pathlib import Path
from typing import Optional

from shared import TEXT_ENCODING, TEXT_ERRORS, build_git_env


def is_git_cmd(cmd: list[str]) -> bool:
    """Check if a command is a git command that needs the restricted env."""
    return bool(cmd) and str(cmd[0]) == 'git'


def run_capture(cmd: list[str],
                cwd: Optional[Path] = None) -> subprocess.CompletedProcess:
    """Execute command and capture output.

    Automatically injects the restricted git environment for git commands.

    Args:
        cmd: Command and arguments to execute.
        cwd: Working directory for the command.

    Returns:
        CompletedProcess with stdout/stderr as strings (undecodable bytes
        replaced, see shared.TEXT_ERRORS).
    """
    env = build_git_env() if is_git_cmd(cmd) else None
    return subprocess.run(cmd, cwd=cwd, capture_output=True,
                          encoding=TEXT_ENCODING, errors=TEXT_ERRORS,
                          check=False, env=env)


def run_git_stdout(args: list[str], cwd: Path) -> str:
    """Run git command and return stdout, or empty string on failure.

    Args:
        args: Git arguments (without 'git' prefix).
        cwd: Working directory.

    Returns:
        Stripped stdout on success, empty string on failure or missing cwd.
    """
    if not cwd.exists():
        return ""
    result = subprocess.run(
        ['git'] + args, cwd=cwd, env=build_git_env(),
        capture_output=True, encoding=TEXT_ENCODING, errors=TEXT_ERRORS,
        check=False
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def force_checkout_branch(cwd: Path, branch: str) -> bool:
    """Check out a branch, escalating cleanup until the switch succeeds.

    A devtool workspace tree is routinely left dirty: builds regenerate
    tracked autotools output (``configure``, ``Makefile.in``, ``aclocal.m4``,
    ``config/*``) and submodule content, and an aborted AI session can leave
    unmerged index entries behind.  A plain ``git checkout`` then fails with
    "Your local changes would be overwritten by checkout", stranding the tree
    on the wrong branch.

    Escalation order — each step only runs if the previous checkout failed,
    so no more state is discarded than necessary:

    1. plain ``checkout``
    2. ``checkout -f`` (discard tracked modifications and unmerged entries)
    3. ``reset --hard`` + submodule ``reset --hard`` then ``checkout -f``
    4. ``clean -fd`` (keeping ``oe-local-files``) then ``checkout -f``

    On success after any forced step, submodule working trees are re-synced to
    the target branch's gitlinks so the tree is coherent for the next
    cherry-pick.  A plain (non-forced) checkout leaves submodules untouched.

    Args:
        cwd: Repository working directory.
        branch: Branch name to check out.

    Returns:
        True if the repo ends up on ``branch``, False otherwise.
    """
    def _checkout(*flags: str) -> bool:
        if run_capture(['git', 'checkout', *flags, branch],
                       cwd=cwd).returncode != 0:
            return False
        # A forced switch leaves submodule working trees at the previous
        # branch's commits, which shows up as a dirty tree and blocks the
        # next cherry-pick.
        if flags and (cwd / '.gitmodules').exists():
            run_capture(['git', 'submodule', 'update', '--init',
                         '--recursive', '--force'], cwd=cwd)
        return True

    if _checkout():
        return True
    if _checkout('-f'):
        return True

    run_capture(['git', 'reset', '--hard', 'HEAD'], cwd=cwd)
    run_capture(['git', 'submodule', 'foreach', '--recursive',
                 'git', 'reset', '--hard'], cwd=cwd)
    if _checkout('-f'):
        return True

    # Last resort: untracked files (e.g. copied from the devtool branch) are
    # shadowing tracked paths on the target branch.  They are regenerated by
    # copy_missing_files_from_devtool() before the next build.
    run_capture(['git', 'clean', '-fd', '-e', 'oe-local-files'], cwd=cwd)
    run_capture(['git', 'submodule', 'foreach', '--recursive',
                 'git', 'clean', '-fd'], cwd=cwd)
    return _checkout('-f')


def run_git_display(args: list[str], cwd: Path) -> None:
    """Run git command with output printed directly (no pager).

    Args:
        args: Git arguments (without 'git' prefix).
        cwd: Working directory.
    """
    subprocess.run(
        ['git', '--no-pager'] + args, cwd=cwd, env=build_git_env(),
        check=False
    )
