# Copyright (C) 2026 Ericsson AB
# SPDX-License-Identifier: MIT
"""Integration test: scope guard recovers from a dirty devtool branch.

Reproduces the reported failure where the AI session left the workspace on
the devtool branch with regenerated autotools files in the tree, so the
guard's ``git checkout <cve-branch>`` aborted with "Your local changes to the
following files would be overwritten by checkout".
"""
import subprocess
from pathlib import Path

from cve_agent.git import revert_unauthorized_changes


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(['git', *args], cwd=cwd, check=True, capture_output=True,
                   text=True)


def _make_workspace(tmp_path: Path) -> Path:
    ws = tmp_path / 'jq'
    ws.mkdir()
    _git(ws, 'init', '-q', '-b', 'main')
    _git(ws, 'config', 'user.email', 'test@example.com')
    _git(ws, 'config', 'user.name', 'Test')
    (ws / 'src.c').write_text('base\n', encoding='utf-8')
    (ws / 'configure').write_text('base\n', encoding='utf-8')
    _git(ws, 'add', '-A')
    _git(ws, 'commit', '-qm', 'base')

    _git(ws, 'checkout', '-q', '-b', 'CVE-2026-39956')
    _git(ws, 'tag', '-f', 'original-version')
    (ws / 'src.c').write_text('fixed\n', encoding='utf-8')
    (ws / 'configure').write_text('cve regenerated\n', encoding='utf-8')
    (ws / 'unrelated.c').write_text('agent scribble\n', encoding='utf-8')
    _git(ws, 'add', '-A')
    _git(ws, 'commit', '-qm', 'CVE fix')

    # Agent ended the session on the devtool branch with a dirty tree
    _git(ws, 'checkout', '-q', '-b', 'devtool', 'main')
    (ws / 'configure').write_text('regenerated by autoreconf\n', encoding='utf-8')
    return ws


def test_recovers_from_dirty_devtool_branch(tmp_path):
    ws = _make_workspace(tmp_path)

    plain = subprocess.run(['git', 'checkout', 'CVE-2026-39956'], cwd=ws,
                           capture_output=True, text=True, check=False)
    assert plain.returncode != 0  # pre-condition: the reported failure

    revert_unauthorized_changes(ws, {'src.c', 'configure'})

    branch = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
                            cwd=ws, capture_output=True, text=True,
                            check=True).stdout.strip()
    assert branch == 'CVE-2026-39956'

    committed = subprocess.run(
        ['git', 'diff', '--name-only', 'original-version..HEAD'], cwd=ws,
        capture_output=True, text=True, check=True).stdout.split()
    assert 'unrelated.c' not in committed
    assert 'src.c' in committed
    assert not (ws / 'unrelated.c').exists()
