# Copyright (C) 2026 Ericsson AB
# SPDX-License-Identifier: MIT
"""Synthetic regression tests for the trusted repository handoff."""
from __future__ import annotations

import json
import os
import subprocess
import time
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from cve_agent import AgentConfig, FailureClass
from cve_agent.handoff import validate_repository_handoff
from cve_agent.knowledge import KnowledgeBase
from cve_agent.openai_tools import FileToolPathPolicy, ToolPolicyError
from cve_agent.orchestrator import _run_cve_pipeline
from cve_agent.session import guarded_session
from cve_corrector.handoff import emit_handoff
from cve_corrector.state import WorkflowState
from shared.handoff import (
    HandoffError,
    read_handoff,
    reference_change_paths,
    validate_handoff_state,
)


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=repo, check=True, capture_output=True, text=True)
    return result.stdout.strip()


def _commit(repo: Path, message: str) -> str:
    _git(repo, "add", "-A")
    _git(repo, "commit", "-m", message)
    return _git(repo, "rev-parse", "HEAD")


def _repo(tmp_path: Path) -> tuple[Path, str]:
    repo = tmp_path / "build" / "workspace" / "sources" / "recipe"
    repo.mkdir(parents=True)
    _git(repo, "init", "-q")
    _git(repo, "config", "user.name", "Test")
    _git(repo, "config", "user.email", "test@example.com")
    (repo / "source.c").write_text("old\n", encoding="utf-8")
    (repo / "generated.txt").write_text("stable\n", encoding="utf-8")
    _commit(repo, "base")
    _git(repo, "tag", "original-version")
    (repo / "source.c").write_text("fixed\n", encoding="utf-8")
    selected = _commit(repo, "fix")
    return repo, selected


def _state(repo: Path, selected: str, **kwargs: object) -> WorkflowState:
    return WorkflowState(
        workspace_path=repo,
        cve_id="CVE-2026-1234",
        recipe="recipe",
        commit_hash=selected,
        hash_details=[],
        meta_layer=None,
        skip_build=False,
        skip_ptest=True,
        **kwargs,
    )


def test_ordinary_handoff_validates_and_generated_file_is_restored(tmp_path):
    repo, selected = _repo(tmp_path)
    (repo / "generated.txt").write_text("generated by build\n", encoding="utf-8")
    state_dir = repo.parent.parent / "cve_corrector"
    manifest = emit_handoff(
        _state(repo, selected, known_generated_paths=["generated.txt"]), state_dir)

    assert (repo / "generated.txt").read_text(encoding="utf-8") == "stable\n"
    assert manifest.allowed_paths == ("source.c",)
    assert manifest.known_generated_paths == ("generated.txt",)
    policy = FileToolPathPolicy(repo, manifest.allowed_paths)
    with pytest.raises(ToolPolicyError):
        policy.authorize_write("generated.txt")
    assert validate_repository_handoff(
        repo, "CVE-2026-1234", required=True) == manifest


def test_unknown_tracked_out_of_scope_fails_with_bounded_manifest(tmp_path):
    repo, selected = _repo(tmp_path)
    (repo / "generated.txt").write_text("unknown source edit\n", encoding="utf-8")
    state_dir = repo.parent.parent / "cve_corrector"

    with pytest.raises(HandoffError, match="HANDOFF_UNKNOWN_OUT_OF_SCOPE"):
        emit_handoff(_state(repo, selected), state_dir)
    persisted = read_handoff(state_dir / "handoffs" / "recipe.json")
    assert persisted.tracked_out_of_scope_paths == ("generated.txt",)


def test_manifest_tamper_and_repository_drift_are_rejected(tmp_path):
    repo, selected = _repo(tmp_path)
    state_dir = repo.parent.parent / "cve_corrector"
    manifest = emit_handoff(_state(repo, selected), state_dir)
    path = state_dir / "handoffs" / "recipe.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    data["allowed_paths"] = ["other.c"]
    path.write_text(json.dumps(data), encoding="utf-8")
    with pytest.raises(HandoffError, match="HANDOFF_DIGEST_MISMATCH"):
        read_handoff(path)

    path.unlink()
    emit_handoff(_state(repo, selected), state_dir)
    (repo / "source.c").write_text("drift\n", encoding="utf-8")
    with pytest.raises(HandoffError, match="HANDOFF_STATE_DRIFT"):
        validate_handoff_state(manifest, repo)


def test_merge_paths_require_and_verify_explicit_mainline(tmp_path):
    repo, _ = _repo(tmp_path)
    (repo / "delete.c").write_text("delete\n", encoding="utf-8")
    (repo / "old.c").write_text("rename\n", encoding="utf-8")
    (repo / "type.c").write_text("regular\n", encoding="utf-8")
    _commit(repo, "seed paths")
    base = _git(repo, "rev-parse", "HEAD")
    _git(repo, "checkout", "-q", "-b", "feature")
    _git(repo, "mv", "old.c", "new.c")
    (repo / "delete.c").unlink()
    (repo / "type.c").unlink()
    os.symlink("source.c", repo / "type.c")
    _commit(repo, "feature net change")
    _git(repo, "checkout", "-q", "master")
    (repo / "main.c").write_text("main\n", encoding="utf-8")
    _commit(repo, "main change")
    _git(repo, "merge", "--no-ff", "-m", "merge fix", "feature")
    merge = _git(repo, "rev-parse", "HEAD")

    with pytest.raises(HandoffError, match="HANDOFF_MERGE_MAINLINE_REQUIRED"):
        reference_change_paths(repo, merge, None)
    with pytest.raises(HandoffError, match="HANDOFF_INVALID_MAINLINE"):
        reference_change_paths(repo, merge, 3)
    paths, parent = reference_change_paths(repo, merge, 1)
    assert parent == _git(repo, "rev-parse", f"{merge}^1")
    assert {"old.c", "new.c", "delete.c", "type.c"} <= set(paths)
    assert base != merge


def test_empty_reference_change_is_rejected(tmp_path):
    repo, _ = _repo(tmp_path)
    _git(repo, "commit", "--allow-empty", "-m", "empty")
    with pytest.raises(HandoffError, match="HANDOFF_EMPTY_ALLOWED_SCOPE"):
        reference_change_paths(repo, _git(repo, "rev-parse", "HEAD"), None)


def test_missing_required_handoff_makes_zero_provider_calls(tmp_path):
    repo, selected = _repo(tmp_path)
    backend = MagicMock()
    with patch("cve_agent.session.get_backend", return_value=backend):
        result = guarded_session(
            tmp_path / "context.md", repo, selected,
            {"hashes": [selected]}, cve_id="CVE-2026-1234",
            require_handoff=True,
        )
    assert not result.resolved
    assert result.failure_reason == "Corrector handoff failed: HANDOFF_MISSING"
    backend.run_session.assert_not_called()


def test_corrector_handoff_error_is_preserved_in_result(tmp_path):
    metadata = tmp_path / "cves.json"
    metadata.write_text(json.dumps({
        "CVE-2026-1234": {"name": "recipe", "hashes": ["a" * 40]},
    }), encoding="utf-8")
    config = AgentConfig(cve_id="CVE-2026-1234", cve_info_path=metadata)
    with patch(
            "cve_agent.orchestrator.run_corrector",
            return_value=(7, "HANDOFF_UNKNOWN_OUT_OF_SCOPE: refused")), patch(
                "cve_agent.orchestrator.guarded_session") as provider:
        result = _run_cve_pipeline(
            config, KnowledgeBase(tmp_path / "knowledge.json"), time.monotonic())
    assert result.failure_class is FailureClass.CORRECTOR_HANDOFF
    assert result.failure_code == "HANDOFF_UNKNOWN_OUT_OF_SCOPE"
    provider.assert_not_called()
